@startuml
actor Utente
participant MainPageView_UI
participant MainPageViewController

Utente -> MainPageView_UI: Clicca su "Aggiungi spesa"
activate MainPageView_UI
MainPageView_UI -> MainPageViewController ++ : addExpenseButtonClick()
create AddExpenseDialog
MainPageViewController -> AddExpenseDialog -- : new

MainPageView_UI -> Utente: Richiede dati spesa
Utente -> MainPageView_UI: Inserisce dati spesa

MainPageView_UI -> AddExpenseDialog ++: Submit Dialog
deactivate MainPageView_UI

AddExpenseDialog -> AddExpenseDialog: validateExpenseData()

alt Dati validi
    AddExpenseDialog -> MainPageViewController : saveExpense()
    destroy AddExpenseDialog

    activate MainPageViewController
    MainPageViewController -> ExpenseRepository: save(entity:Expense)
    activate ExpenseRepository
    ExpenseRepository --> MainPageViewController: Conferma salvataggio
    deactivate ExpenseRepository
    MainPageViewController -> MainPageView_UI : Conferma aggiunta spesa
    deactivate MainPageViewController
    activate MainPageView_UI

    MainPageView_UI -> MainPageView_UI : Aggiorna tabella spese
    deactivate MainPageView_UI
else Dati non validi
    AddExpenseDialog -> MainPageViewController : Return error
    destroy AddExpenseDialog

    activate MainPageViewController
    MainPageViewController -> MainPageView_UI -- : Notifica errore validazione
    activate AddExpenseDialog

    activate MainPageView_UI
    MainPageView_UI -> Utente: Mostra messaggio di errore
    deactivate MainPageView_UI
end

@enduml