@startuml
actor User

package "Expense Tracker" {
  [View] as view
  [Model] as model
  [Controller] as controller
  database "Postgresql" as db
}

model -> db : stores data
db --> model : reads data

view -> User : sees
view <-- model : updates

controller -> model : manipulates

User --> controller : uses

@enduml